name: SonarQube Scan
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  sonar-analysis:
    runs-on: ubuntu-22.04 # Label native runner yang Anda miliki
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Execute SonarScanner
        env:
          # Token autentikasi yang dibuat dari halaman profil SonarQube Anda
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: "http://192.168.33.116:9002"
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ github.event.repository.name }} \
            -Dsonar.sources=. \
            -Dsonar.exclusions=vendor/**,node_modules/**,tests/**
